version: "3"
services:
  crw_nginx:
    image: nginx
    network_mode: host
    extra_hosts:
      host.docker.internal: host-gateway
    ports:
      - "80:80"
    volumes:
      - ./.cromwell/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/usr/share/nginx/html
