version: "3"
services:
  nginx:
    image: certbot/certbot
    command: "certonly"
    volumes:
      - ./.cromwell/letsencrypt:/etc/letsencrypt
      - ./.cromwell/letsencrypt/lib:/var/lib/letsencrypt