const { MigrationInterface, QueryRunner } = require("typeorm");

module.exports = class init1628231245845 {
    name = 'init1628231245845'

    async up(queryRunner) {
        await queryRunner.query(`CREATE TABLE "crw_base_page_entity" ("id" SERIAL NOT NULL, "slug" character varying, "pageTitle" character varying, "pageDescription" character varying, "createDate" TIMESTAMP NOT NULL DEFAULT now(), "updateDate" TIMESTAMP NOT NULL DEFAULT now(), "isEnabled" boolean DEFAULT true, CONSTRAINT "UQ_33d156210ae42177f24eb55b524" UNIQUE ("slug"), CONSTRAINT "PK_f90bc99c36e17ac27bea436a529" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "crw_attribute" ("id" SERIAL NOT NULL, "slug" character varying, "pageTitle" character varying, "pageDescription" character varying, "createDate" TIMESTAMP NOT NULL DEFAULT now(), "updateDate" TIMESTAMP NOT NULL DEFAULT now(), "isEnabled" boolean DEFAULT true, "key" character varying NOT NULL, "valuesJSON" text, "type" character varying NOT NULL, "icon" character varying(300), "required" boolean, CONSTRAINT "UQ_21d04deefef2e9d62ed19ba759a" UNIQUE ("slug"), CONSTRAINT "PK_14123e1bfce87c730d9f9b2e7ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "crw_cms" ("id" SERIAL NOT NULL, "slug" character varying, "pageTitle" character varying, "pageDescription" character varying, "createDate" TIMESTAMP NOT NULL DEFAULT now(), "updateDate" TIMESTAMP NOT NULL DEFAULT now(), "isEnabled" boolean DEFAULT true, "_publicSettings" text, "_adminSettings" text, "_internalSettings" text, CONSTRAINT "UQ_45a249e9f534b6af909ffedf0d2" UNIQUE ("slug"), CONSTRAINT "PK_35aee121b80f1702414cd3d86a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "crw_order" ("id" SERIAL NOT NULL, "slug" character varying, "pageTitle" character varying, "pageDescription" character varying, "createDate" TIMESTAMP NOT NULL DEFAULT now(), "updateDate" TIMESTAMP NOT NULL DEFAULT now(), "isEnabled" boolean DEFAULT true, "status" character varying, "cart" text, "orderTotalPrice" double precision, "cartTotalPrice" double precision, "cartOldTotalPrice" double precision, "shippingPrice" double precision, "totalQnt" double precision, "userId" character varying, "customerName" character varying, "customerPhone" character varying, "customerEmail" character varying, "customerAddress" character varying, "shippingMethod" character varying, "paymentMethod" character varying, "customerComment" character varying, "currency" character varying, CONSTRAINT "UQ_7a2428bdc18f7abd37585706687" UNIQUE ("slug"), CONSTRAINT "PK_f9516631047341dd5a92da55ed6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_56caac5bbc2683720ddd655a23" ON "crw_order" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_86c22318de90222b57a2f0ac90" ON "crw_order" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a71afe78a44fdebe245d06c0fb" ON "crw_order" ("customerName") `);
        await queryRunner.query(`CREATE INDEX "IDX_8bb01ee9a429f70390bbedbaf6" ON "crw_order" ("customerPhone") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d115ee42c627f4c5f5ea6d12a" ON "crw_order" ("customerEmail") `);
        await queryRunner.query(`CREATE TABLE "crw_page_stats" ("id" SERIAL NOT NULL, "pageRoute" character varying NOT NULL, "pageName" character varying, "pageId" character varying, "views" integer, CONSTRAINT "PK_f774ad09d3d69ddbdef96705010" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "crw_plugin" ("id" SERIAL NOT NULL, "slug" character varying, "pageTitle" character varying, "pageDescription" character varying, "createDate" TIMESTAMP NOT NULL DEFAULT now(), "updateDate" TIMESTAMP NOT NULL DEFAULT now(), "isEnabled" boolean DEFAULT true, "name" character varying NOT NULL, "version" character varying, "title" character varying, "isInstalled" boolean NOT NULL, "hasAdminBundle" boolean, "settings" text, "defaultSettings" text, "moduleInfo" text, "isUpdating" boolean, CONSTRAINT "UQ_067de3d2c7d9e0e6fc733c7ba59" UNIQUE ("slug"), CONSTRAINT "PK_89a31be444f5f741a1d247f6275" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "crw_post_comment" ("id" SERIAL NOT NULL, "slug" character varying, "pageTitle" character varying, "pageDescription" character varying, "createDate" TIMESTAMP NOT NULL DEFAULT now(), "updateDate" TIMESTAMP NOT NULL DEFAULT now(), "isEnabled" boolean DEFAULT true, "postId" integer NOT NULL, "title" character varying, "comment" text, "userEmail" character varying, "userName" character varying, "userId" character varying, "approved" boolean, CONSTRAINT "UQ_0c41e89299843ea6cd5bb1e10b3" UNIQUE ("slug"), CONSTRAINT "PK_29b13761ab698fe448554a3e38b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_787534d5ddf971c1b85d99c88c" ON "crw_post_comment" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_16527a7e9f22a68a274e61d6da" ON "crw_post_comment" ("userEmail") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb0a2cf3605d77131907fb4664" ON "crw_post_comment" ("userId") `);
        await queryRunner.query(`CREATE TABLE "crw_tag" ("id" SERIAL NOT NULL, "slug" character varying, "pageTitle" character varying, "pageDescription" character varying, "createDate" TIMESTAMP NOT NULL DEFAULT now(), "updateDate" TIMESTAMP NOT NULL DEFAULT now(), "isEnabled" boolean DEFAULT true, "name" character varying NOT NULL, "color" character varying, "image" character varying, "description" text, "descriptionDelta" text, CONSTRAINT "UQ_3ad1ae94ac65ac5cf6ef4a97fd4" UNIQUE ("slug"), CONSTRAINT "UQ_ecaa69a0357666eebdd48c8c755" UNIQUE ("name"), CONSTRAINT "PK_9f320f9f26d7779a37a1202d09a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "crw_post" ("id" SERIAL NOT NULL, "slug" character varying, "pageTitle" character varying, "pageDescription" character varying, "createDate" TIMESTAMP NOT NULL DEFAULT now(), "updateDate" TIMESTAMP NOT NULL DEFAULT now(), "isEnabled" boolean DEFAULT true, "title" character varying, "authorId" character varying NOT NULL, "content" text, "delta" text, "excerpt" character varying(5000), "mainImage" character varying(300), "readTime" character varying, "published" boolean, "publishDate" TIMESTAMP, "featured" boolean, CONSTRAINT "UQ_29f14d08659ef8a3230e244708e" UNIQUE ("slug"), CONSTRAINT "PK_5ab22641659adcdaff7704b6c5c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e47953e4571dce4050c9524443" ON "crw_post" ("title") `);
        await queryRunner.query(`CREATE INDEX "IDX_35c1445265a8d5362e06167ae3" ON "crw_post" ("authorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d98eb30db4dfb464ce54c1957" ON "crw_post" ("published") `);
        await queryRunner.query(`CREATE INDEX "IDX_0977d4805adadb696f735445ee" ON "crw_post" ("featured") `);
        await queryRunner.query(`CREATE TABLE "crw_product_category" ("id" SERIAL NOT NULL, "slug" character varying, "pageTitle" character varying, "pageDescription" character varying, "createDate" TIMESTAMP NOT NULL DEFAULT now(), "updateDate" TIMESTAMP NOT NULL DEFAULT now(), "isEnabled" boolean DEFAULT true, "name" character varying NOT NULL, "mainImage" character varying(300), "description" text, "descriptionDelta" text, "parentId" integer, CONSTRAINT "UQ_273d34ee465b63376bead18bbf2" UNIQUE ("slug"), CONSTRAINT "PK_59bfab9f694d339b5c3c857459b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "crw_product_review" ("id" SERIAL NOT NULL, "slug" character varying, "pageTitle" character varying, "pageDescription" character varying, "createDate" TIMESTAMP NOT NULL DEFAULT now(), "updateDate" TIMESTAMP NOT NULL DEFAULT now(), "isEnabled" boolean DEFAULT true, "productId" integer NOT NULL, "title" character varying, "description" text, "rating" double precision, "userEmail" character varying, "userName" character varying, "userId" character varying, "approved" boolean, CONSTRAINT "UQ_2fa3845bbaf6607041282074f3a" UNIQUE ("slug"), CONSTRAINT "PK_a5cf4a8450a9f6dbd2652a83fc1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_487be848a7b34339aec3524e22" ON "crw_product_review" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1cdd15bc1a00fb7500146d9cd" ON "crw_product_review" ("rating") `);
        await queryRunner.query(`CREATE INDEX "IDX_399b21eccdf612065456fb2610" ON "crw_product_review" ("userEmail") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc5af49e3e348deae17df11497" ON "crw_product_review" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b096b1be8dd42fe22ddc88821d" ON "crw_product_review" ("approved") `);
        await queryRunner.query(`CREATE TABLE "crw_product" ("id" SERIAL NOT NULL, "slug" character varying, "pageTitle" character varying, "pageDescription" character varying, "createDate" TIMESTAMP NOT NULL DEFAULT now(), "updateDate" TIMESTAMP NOT NULL DEFAULT now(), "isEnabled" boolean DEFAULT true, "name" character varying, "price" double precision, "oldPrice" double precision, "sku" character varying, "mainImage" character varying(300), "images" text, "description" text, "descriptionDelta" text, "attributesJSON" text, "averageRating" numeric, "reviewsCount" integer, CONSTRAINT "UQ_404785f00e4d88df4fa5783830b" UNIQUE ("slug"), CONSTRAINT "PK_eb9777ea5f5b04f2cbba1e0af09" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e734039ba75ee043d3c61466de" ON "crw_product" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4383ddcc0498cfacd641f9cf8" ON "crw_product" ("price") `);
        await queryRunner.query(`CREATE INDEX "IDX_c717d9265ea3490790ee35edcd" ON "crw_product" ("sku") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce9152d8ef22b16ce86a6e0fd8" ON "crw_product" ("attributesJSON") `);
        await queryRunner.query(`CREATE TABLE "crw_theme" ("id" SERIAL NOT NULL, "slug" character varying, "pageTitle" character varying, "pageDescription" character varying, "createDate" TIMESTAMP NOT NULL DEFAULT now(), "updateDate" TIMESTAMP NOT NULL DEFAULT now(), "isEnabled" boolean DEFAULT true, "name" character varying NOT NULL, "version" character varying, "title" character varying, "isInstalled" boolean NOT NULL, "hasAdminBundle" boolean, "settings" text, "defaultSettings" text, "moduleInfo" text, "isUpdating" boolean, CONSTRAINT "UQ_05d0c5a03358df4a5fc355eb7fc" UNIQUE ("slug"), CONSTRAINT "PK_e1ce51262721c84f8d0b0e167c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "crw_user" ("id" SERIAL NOT NULL, "slug" character varying, "pageTitle" character varying, "pageDescription" character varying, "createDate" TIMESTAMP NOT NULL DEFAULT now(), "updateDate" TIMESTAMP NOT NULL DEFAULT now(), "isEnabled" boolean DEFAULT true, "fullName" character varying, "email" character varying, "avatar" character varying, "bio" character varying(6000), "role" character varying, "address" character varying(1000), "phone" character varying, "password" character varying NOT NULL, "refreshToken" character varying(500), "resetPasswordCode" character varying, "resetPasswordDate" TIMESTAMP, CONSTRAINT "UQ_86fcd952549ae797ab020043b23" UNIQUE ("slug"), CONSTRAINT "UQ_4544ef20d7756aad6b7a49d8133" UNIQUE ("email"), CONSTRAINT "PK_d1e2d7b6f6f40bef308ba789a97" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0537e4a35e2b1842afc531deab" ON "crw_user" ("fullName") `);
        await queryRunner.query(`CREATE INDEX "IDX_850a536df6641e90872f905e74" ON "crw_user" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_644eed41dbcadfe2e3e634ba84" ON "crw_user" ("phone") `);
        await queryRunner.query(`CREATE TABLE "crw_post_tags_tag" ("postId" integer NOT NULL, "tagId" integer NOT NULL, CONSTRAINT "PK_96ce8d01fd93486defe1bfe23df" PRIMARY KEY ("postId", "tagId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f24f47df26e67c493b68bfc75b" ON "crw_post_tags_tag" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6c786f2afb686050d8233fdc6e" ON "crw_post_tags_tag" ("tagId") `);
        await queryRunner.query(`CREATE TABLE "crw_product_categories_product_category" ("productId" integer NOT NULL, "productCategoryId" integer NOT NULL, CONSTRAINT "PK_7236365889528039c2f20767a16" PRIMARY KEY ("productId", "productCategoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8056740044bde85c6535e4cc6c" ON "crw_product_categories_product_category" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f4f41beb6142f70af17b37ff50" ON "crw_product_categories_product_category" ("productCategoryId") `);
        await queryRunner.query(`CREATE TABLE "crw_product_category_closure" ("id_ancestor" integer NOT NULL, "id_descendant" integer NOT NULL, CONSTRAINT "PK_1f42bca2566c624ff114986df40" PRIMARY KEY ("id_ancestor", "id_descendant"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9463c9a5893b1efb969e9a21c5" ON "crw_product_category_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_bc8936d152e18bc99150472594" ON "crw_product_category_closure" ("id_descendant") `);
        await queryRunner.query(`ALTER TABLE "crw_post_comment" ADD CONSTRAINT "FK_787534d5ddf971c1b85d99c88c3" FOREIGN KEY ("postId") REFERENCES "crw_post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crw_product_category" ADD CONSTRAINT "FK_e7959ee49453ac5342ed33c2f0f" FOREIGN KEY ("parentId") REFERENCES "crw_product_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crw_product_review" ADD CONSTRAINT "FK_487be848a7b34339aec3524e221" FOREIGN KEY ("productId") REFERENCES "crw_product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crw_post_tags_tag" ADD CONSTRAINT "FK_f24f47df26e67c493b68bfc75bb" FOREIGN KEY ("postId") REFERENCES "crw_post"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crw_post_tags_tag" ADD CONSTRAINT "FK_6c786f2afb686050d8233fdc6e7" FOREIGN KEY ("tagId") REFERENCES "crw_tag"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crw_product_categories_product_category" ADD CONSTRAINT "FK_8056740044bde85c6535e4cc6c9" FOREIGN KEY ("productId") REFERENCES "crw_product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crw_product_categories_product_category" ADD CONSTRAINT "FK_f4f41beb6142f70af17b37ff50f" FOREIGN KEY ("productCategoryId") REFERENCES "crw_product_category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crw_product_category_closure" ADD CONSTRAINT "FK_9463c9a5893b1efb969e9a21c59" FOREIGN KEY ("id_ancestor") REFERENCES "crw_product_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crw_product_category_closure" ADD CONSTRAINT "FK_bc8936d152e18bc991504725944" FOREIGN KEY ("id_descendant") REFERENCES "crw_product_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    async down(queryRunner) {
        await queryRunner.query(`ALTER TABLE "crw_product_category_closure" DROP CONSTRAINT "FK_bc8936d152e18bc991504725944"`);
        await queryRunner.query(`ALTER TABLE "crw_product_category_closure" DROP CONSTRAINT "FK_9463c9a5893b1efb969e9a21c59"`);
        await queryRunner.query(`ALTER TABLE "crw_product_categories_product_category" DROP CONSTRAINT "FK_f4f41beb6142f70af17b37ff50f"`);
        await queryRunner.query(`ALTER TABLE "crw_product_categories_product_category" DROP CONSTRAINT "FK_8056740044bde85c6535e4cc6c9"`);
        await queryRunner.query(`ALTER TABLE "crw_post_tags_tag" DROP CONSTRAINT "FK_6c786f2afb686050d8233fdc6e7"`);
        await queryRunner.query(`ALTER TABLE "crw_post_tags_tag" DROP CONSTRAINT "FK_f24f47df26e67c493b68bfc75bb"`);
        await queryRunner.query(`ALTER TABLE "crw_product_review" DROP CONSTRAINT "FK_487be848a7b34339aec3524e221"`);
        await queryRunner.query(`ALTER TABLE "crw_product_category" DROP CONSTRAINT "FK_e7959ee49453ac5342ed33c2f0f"`);
        await queryRunner.query(`ALTER TABLE "crw_post_comment" DROP CONSTRAINT "FK_787534d5ddf971c1b85d99c88c3"`);
        await queryRunner.query(`DROP INDEX "IDX_bc8936d152e18bc99150472594"`);
        await queryRunner.query(`DROP INDEX "IDX_9463c9a5893b1efb969e9a21c5"`);
        await queryRunner.query(`DROP TABLE "crw_product_category_closure"`);
        await queryRunner.query(`DROP INDEX "IDX_f4f41beb6142f70af17b37ff50"`);
        await queryRunner.query(`DROP INDEX "IDX_8056740044bde85c6535e4cc6c"`);
        await queryRunner.query(`DROP TABLE "crw_product_categories_product_category"`);
        await queryRunner.query(`DROP INDEX "IDX_6c786f2afb686050d8233fdc6e"`);
        await queryRunner.query(`DROP INDEX "IDX_f24f47df26e67c493b68bfc75b"`);
        await queryRunner.query(`DROP TABLE "crw_post_tags_tag"`);
        await queryRunner.query(`DROP INDEX "IDX_644eed41dbcadfe2e3e634ba84"`);
        await queryRunner.query(`DROP INDEX "IDX_850a536df6641e90872f905e74"`);
        await queryRunner.query(`DROP INDEX "IDX_0537e4a35e2b1842afc531deab"`);
        await queryRunner.query(`DROP TABLE "crw_user"`);
        await queryRunner.query(`DROP TABLE "crw_theme"`);
        await queryRunner.query(`DROP INDEX "IDX_ce9152d8ef22b16ce86a6e0fd8"`);
        await queryRunner.query(`DROP INDEX "IDX_c717d9265ea3490790ee35edcd"`);
        await queryRunner.query(`DROP INDEX "IDX_a4383ddcc0498cfacd641f9cf8"`);
        await queryRunner.query(`DROP INDEX "IDX_e734039ba75ee043d3c61466de"`);
        await queryRunner.query(`DROP TABLE "crw_product"`);
        await queryRunner.query(`DROP INDEX "IDX_b096b1be8dd42fe22ddc88821d"`);
        await queryRunner.query(`DROP INDEX "IDX_dc5af49e3e348deae17df11497"`);
        await queryRunner.query(`DROP INDEX "IDX_399b21eccdf612065456fb2610"`);
        await queryRunner.query(`DROP INDEX "IDX_c1cdd15bc1a00fb7500146d9cd"`);
        await queryRunner.query(`DROP INDEX "IDX_487be848a7b34339aec3524e22"`);
        await queryRunner.query(`DROP TABLE "crw_product_review"`);
        await queryRunner.query(`DROP TABLE "crw_product_category"`);
        await queryRunner.query(`DROP INDEX "IDX_0977d4805adadb696f735445ee"`);
        await queryRunner.query(`DROP INDEX "IDX_8d98eb30db4dfb464ce54c1957"`);
        await queryRunner.query(`DROP INDEX "IDX_35c1445265a8d5362e06167ae3"`);
        await queryRunner.query(`DROP INDEX "IDX_e47953e4571dce4050c9524443"`);
        await queryRunner.query(`DROP TABLE "crw_post"`);
        await queryRunner.query(`DROP TABLE "crw_tag"`);
        await queryRunner.query(`DROP INDEX "IDX_cb0a2cf3605d77131907fb4664"`);
        await queryRunner.query(`DROP INDEX "IDX_16527a7e9f22a68a274e61d6da"`);
        await queryRunner.query(`DROP INDEX "IDX_787534d5ddf971c1b85d99c88c"`);
        await queryRunner.query(`DROP TABLE "crw_post_comment"`);
        await queryRunner.query(`DROP TABLE "crw_plugin"`);
        await queryRunner.query(`DROP TABLE "crw_page_stats"`);
        await queryRunner.query(`DROP INDEX "IDX_0d115ee42c627f4c5f5ea6d12a"`);
        await queryRunner.query(`DROP INDEX "IDX_8bb01ee9a429f70390bbedbaf6"`);
        await queryRunner.query(`DROP INDEX "IDX_a71afe78a44fdebe245d06c0fb"`);
        await queryRunner.query(`DROP INDEX "IDX_86c22318de90222b57a2f0ac90"`);
        await queryRunner.query(`DROP INDEX "IDX_56caac5bbc2683720ddd655a23"`);
        await queryRunner.query(`DROP TABLE "crw_order"`);
        await queryRunner.query(`DROP TABLE "crw_cms"`);
        await queryRunner.query(`DROP TABLE "crw_attribute"`);
        await queryRunner.query(`DROP TABLE "crw_base_page_entity"`);
    }
}
