const { MigrationInterface, QueryRunner } = require("typeorm");

module.exports = class init1627970410174 {
    name = 'init1627970410174'

    async up(queryRunner) {
        await queryRunner.query(`CREATE TABLE "crw_base_page_entity" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), CONSTRAINT "UQ_33d156210ae42177f24eb55b524" UNIQUE ("slug"))`);
        await queryRunner.query(`CREATE TABLE "crw_attribute" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "key" varchar NOT NULL, "valuesJSON" text, "type" varchar NOT NULL, "icon" varchar(300), "required" boolean, CONSTRAINT "UQ_21d04deefef2e9d62ed19ba759a" UNIQUE ("slug"))`);
        await queryRunner.query(`CREATE TABLE "crw_cms" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "themeName" varchar NOT NULL, "protocol" varchar, "defaultPageSize" integer, "timezone" integer, "language" varchar, "favicon" varchar(300), "logo" varchar(300), "headHtml" text, "footerHtml" text, "defaultShippingPrice" float, "_currencies" text, "version" varchar, "versions" varchar(2000), "installed" boolean, "beta" boolean, "smtpConnectionString" varchar(400), "sendFromEmail" varchar, "isUpdating" boolean, "_adminSettings" text, CONSTRAINT "UQ_45a249e9f534b6af909ffedf0d2" UNIQUE ("slug"))`);
        await queryRunner.query(`CREATE TABLE "crw_order" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "status" varchar, "cart" text, "orderTotalPrice" float, "cartTotalPrice" float, "cartOldTotalPrice" float, "shippingPrice" float, "totalQnt" float, "userId" varchar, "customerName" varchar, "customerPhone" varchar, "customerEmail" varchar, "customerAddress" varchar, "shippingMethod" varchar, "paymentMethod" varchar, "customerComment" varchar, "currency" varchar, CONSTRAINT "UQ_7a2428bdc18f7abd37585706687" UNIQUE ("slug"))`);
        await queryRunner.query(`CREATE INDEX "IDX_56caac5bbc2683720ddd655a23" ON "crw_order" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_86c22318de90222b57a2f0ac90" ON "crw_order" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a71afe78a44fdebe245d06c0fb" ON "crw_order" ("customerName") `);
        await queryRunner.query(`CREATE INDEX "IDX_8bb01ee9a429f70390bbedbaf6" ON "crw_order" ("customerPhone") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d115ee42c627f4c5f5ea6d12a" ON "crw_order" ("customerEmail") `);
        await queryRunner.query(`CREATE TABLE "crw_page_stats" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "pageRoute" varchar NOT NULL, "pageName" varchar, "pageId" varchar, "views" integer)`);
        await queryRunner.query(`CREATE TABLE "crw_plugin" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "name" varchar NOT NULL, "version" varchar, "title" varchar, "isInstalled" boolean NOT NULL, "hasAdminBundle" boolean, "settings" text, "defaultSettings" text, "moduleInfo" text, "isUpdating" boolean, CONSTRAINT "UQ_067de3d2c7d9e0e6fc733c7ba59" UNIQUE ("slug"))`);
        await queryRunner.query(`CREATE TABLE "crw_post_comment" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "postId" integer NOT NULL, "title" varchar, "comment" text, "userEmail" varchar, "userName" varchar, "userId" varchar, "approved" boolean, CONSTRAINT "UQ_0c41e89299843ea6cd5bb1e10b3" UNIQUE ("slug"))`);
        await queryRunner.query(`CREATE INDEX "IDX_787534d5ddf971c1b85d99c88c" ON "crw_post_comment" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_16527a7e9f22a68a274e61d6da" ON "crw_post_comment" ("userEmail") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb0a2cf3605d77131907fb4664" ON "crw_post_comment" ("userId") `);
        await queryRunner.query(`CREATE TABLE "crw_tag" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "name" varchar NOT NULL, "color" varchar, "image" varchar, "description" text, "descriptionDelta" text, CONSTRAINT "UQ_3ad1ae94ac65ac5cf6ef4a97fd4" UNIQUE ("slug"), CONSTRAINT "UQ_ecaa69a0357666eebdd48c8c755" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "crw_post" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "title" varchar, "authorId" varchar NOT NULL, "content" text, "delta" text, "excerpt" varchar(5000), "mainImage" varchar(300), "readTime" varchar, "published" boolean, "publishDate" datetime, "featured" boolean, CONSTRAINT "UQ_29f14d08659ef8a3230e244708e" UNIQUE ("slug"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e47953e4571dce4050c9524443" ON "crw_post" ("title") `);
        await queryRunner.query(`CREATE INDEX "IDX_35c1445265a8d5362e06167ae3" ON "crw_post" ("authorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d98eb30db4dfb464ce54c1957" ON "crw_post" ("published") `);
        await queryRunner.query(`CREATE INDEX "IDX_0977d4805adadb696f735445ee" ON "crw_post" ("featured") `);
        await queryRunner.query(`CREATE TABLE "crw_product_category" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "name" varchar NOT NULL, "mainImage" varchar(300), "description" text, "descriptionDelta" text, "parentId" integer, CONSTRAINT "UQ_273d34ee465b63376bead18bbf2" UNIQUE ("slug"))`);
        await queryRunner.query(`CREATE TABLE "crw_product_review" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "productId" integer NOT NULL, "title" varchar, "description" text, "rating" float, "userEmail" varchar, "userName" varchar, "userId" varchar, "approved" boolean, CONSTRAINT "UQ_2fa3845bbaf6607041282074f3a" UNIQUE ("slug"))`);
        await queryRunner.query(`CREATE INDEX "IDX_487be848a7b34339aec3524e22" ON "crw_product_review" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1cdd15bc1a00fb7500146d9cd" ON "crw_product_review" ("rating") `);
        await queryRunner.query(`CREATE INDEX "IDX_399b21eccdf612065456fb2610" ON "crw_product_review" ("userEmail") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc5af49e3e348deae17df11497" ON "crw_product_review" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b096b1be8dd42fe22ddc88821d" ON "crw_product_review" ("approved") `);
        await queryRunner.query(`CREATE TABLE "crw_product" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "name" varchar, "price" float, "oldPrice" float, "sku" varchar, "mainImage" varchar(300), "images" text, "description" text, "descriptionDelta" text, "attributesJSON" text, "averageRating" decimal, "reviewsCount" integer, CONSTRAINT "UQ_404785f00e4d88df4fa5783830b" UNIQUE ("slug"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e734039ba75ee043d3c61466de" ON "crw_product" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4383ddcc0498cfacd641f9cf8" ON "crw_product" ("price") `);
        await queryRunner.query(`CREATE INDEX "IDX_c717d9265ea3490790ee35edcd" ON "crw_product" ("sku") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce9152d8ef22b16ce86a6e0fd8" ON "crw_product" ("attributesJSON") `);
        await queryRunner.query(`CREATE TABLE "crw_theme" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "name" varchar NOT NULL, "version" varchar, "title" varchar, "isInstalled" boolean NOT NULL, "hasAdminBundle" boolean, "settings" text, "defaultSettings" text, "moduleInfo" text, "isUpdating" boolean, CONSTRAINT "UQ_05d0c5a03358df4a5fc355eb7fc" UNIQUE ("slug"))`);
        await queryRunner.query(`CREATE TABLE "crw_user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "fullName" varchar, "email" varchar, "avatar" varchar, "bio" varchar(6000), "role" varchar, "address" varchar(1000), "phone" varchar, "password" varchar NOT NULL, "refreshToken" varchar(500), "resetPasswordCode" varchar, "resetPasswordDate" datetime, CONSTRAINT "UQ_86fcd952549ae797ab020043b23" UNIQUE ("slug"), CONSTRAINT "UQ_4544ef20d7756aad6b7a49d8133" UNIQUE ("email"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0537e4a35e2b1842afc531deab" ON "crw_user" ("fullName") `);
        await queryRunner.query(`CREATE INDEX "IDX_850a536df6641e90872f905e74" ON "crw_user" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_644eed41dbcadfe2e3e634ba84" ON "crw_user" ("phone") `);
        await queryRunner.query(`CREATE TABLE "crw_post_tags_tag" ("postId" integer NOT NULL, "tagId" integer NOT NULL, PRIMARY KEY ("postId", "tagId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f24f47df26e67c493b68bfc75b" ON "crw_post_tags_tag" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6c786f2afb686050d8233fdc6e" ON "crw_post_tags_tag" ("tagId") `);
        await queryRunner.query(`CREATE TABLE "crw_product_categories_product_category" ("productId" integer NOT NULL, "productCategoryId" integer NOT NULL, PRIMARY KEY ("productId", "productCategoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8056740044bde85c6535e4cc6c" ON "crw_product_categories_product_category" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f4f41beb6142f70af17b37ff50" ON "crw_product_categories_product_category" ("productCategoryId") `);
        await queryRunner.query(`CREATE TABLE "crw_product_category_closure" ("id_ancestor" integer NOT NULL, "id_descendant" integer NOT NULL, PRIMARY KEY ("id_ancestor", "id_descendant"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9463c9a5893b1efb969e9a21c5" ON "crw_product_category_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_bc8936d152e18bc99150472594" ON "crw_product_category_closure" ("id_descendant") `);
        await queryRunner.query(`DROP INDEX "IDX_787534d5ddf971c1b85d99c88c"`);
        await queryRunner.query(`DROP INDEX "IDX_16527a7e9f22a68a274e61d6da"`);
        await queryRunner.query(`DROP INDEX "IDX_cb0a2cf3605d77131907fb4664"`);
        await queryRunner.query(`CREATE TABLE "temporary_crw_post_comment" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "postId" integer NOT NULL, "title" varchar, "comment" text, "userEmail" varchar, "userName" varchar, "userId" varchar, "approved" boolean, CONSTRAINT "UQ_0c41e89299843ea6cd5bb1e10b3" UNIQUE ("slug"), CONSTRAINT "FK_787534d5ddf971c1b85d99c88c3" FOREIGN KEY ("postId") REFERENCES "crw_post" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_crw_post_comment"("id", "slug", "pageTitle", "pageDescription", "createDate", "updateDate", "isEnabled", "postId", "title", "comment", "userEmail", "userName", "userId", "approved") SELECT "id", "slug", "pageTitle", "pageDescription", "createDate", "updateDate", "isEnabled", "postId", "title", "comment", "userEmail", "userName", "userId", "approved" FROM "crw_post_comment"`);
        await queryRunner.query(`DROP TABLE "crw_post_comment"`);
        await queryRunner.query(`ALTER TABLE "temporary_crw_post_comment" RENAME TO "crw_post_comment"`);
        await queryRunner.query(`CREATE INDEX "IDX_787534d5ddf971c1b85d99c88c" ON "crw_post_comment" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_16527a7e9f22a68a274e61d6da" ON "crw_post_comment" ("userEmail") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb0a2cf3605d77131907fb4664" ON "crw_post_comment" ("userId") `);
        await queryRunner.query(`CREATE TABLE "temporary_crw_product_category" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "name" varchar NOT NULL, "mainImage" varchar(300), "description" text, "descriptionDelta" text, "parentId" integer, CONSTRAINT "UQ_273d34ee465b63376bead18bbf2" UNIQUE ("slug"), CONSTRAINT "FK_e7959ee49453ac5342ed33c2f0f" FOREIGN KEY ("parentId") REFERENCES "crw_product_category" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_crw_product_category"("id", "slug", "pageTitle", "pageDescription", "createDate", "updateDate", "isEnabled", "name", "mainImage", "description", "descriptionDelta", "parentId") SELECT "id", "slug", "pageTitle", "pageDescription", "createDate", "updateDate", "isEnabled", "name", "mainImage", "description", "descriptionDelta", "parentId" FROM "crw_product_category"`);
        await queryRunner.query(`DROP TABLE "crw_product_category"`);
        await queryRunner.query(`ALTER TABLE "temporary_crw_product_category" RENAME TO "crw_product_category"`);
        await queryRunner.query(`DROP INDEX "IDX_487be848a7b34339aec3524e22"`);
        await queryRunner.query(`DROP INDEX "IDX_c1cdd15bc1a00fb7500146d9cd"`);
        await queryRunner.query(`DROP INDEX "IDX_399b21eccdf612065456fb2610"`);
        await queryRunner.query(`DROP INDEX "IDX_dc5af49e3e348deae17df11497"`);
        await queryRunner.query(`DROP INDEX "IDX_b096b1be8dd42fe22ddc88821d"`);
        await queryRunner.query(`CREATE TABLE "temporary_crw_product_review" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "productId" integer NOT NULL, "title" varchar, "description" text, "rating" float, "userEmail" varchar, "userName" varchar, "userId" varchar, "approved" boolean, CONSTRAINT "UQ_2fa3845bbaf6607041282074f3a" UNIQUE ("slug"), CONSTRAINT "FK_487be848a7b34339aec3524e221" FOREIGN KEY ("productId") REFERENCES "crw_product" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_crw_product_review"("id", "slug", "pageTitle", "pageDescription", "createDate", "updateDate", "isEnabled", "productId", "title", "description", "rating", "userEmail", "userName", "userId", "approved") SELECT "id", "slug", "pageTitle", "pageDescription", "createDate", "updateDate", "isEnabled", "productId", "title", "description", "rating", "userEmail", "userName", "userId", "approved" FROM "crw_product_review"`);
        await queryRunner.query(`DROP TABLE "crw_product_review"`);
        await queryRunner.query(`ALTER TABLE "temporary_crw_product_review" RENAME TO "crw_product_review"`);
        await queryRunner.query(`CREATE INDEX "IDX_487be848a7b34339aec3524e22" ON "crw_product_review" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1cdd15bc1a00fb7500146d9cd" ON "crw_product_review" ("rating") `);
        await queryRunner.query(`CREATE INDEX "IDX_399b21eccdf612065456fb2610" ON "crw_product_review" ("userEmail") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc5af49e3e348deae17df11497" ON "crw_product_review" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b096b1be8dd42fe22ddc88821d" ON "crw_product_review" ("approved") `);
        await queryRunner.query(`DROP INDEX "IDX_f24f47df26e67c493b68bfc75b"`);
        await queryRunner.query(`DROP INDEX "IDX_6c786f2afb686050d8233fdc6e"`);
        await queryRunner.query(`CREATE TABLE "temporary_crw_post_tags_tag" ("postId" integer NOT NULL, "tagId" integer NOT NULL, CONSTRAINT "FK_f24f47df26e67c493b68bfc75bb" FOREIGN KEY ("postId") REFERENCES "crw_post" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_6c786f2afb686050d8233fdc6e7" FOREIGN KEY ("tagId") REFERENCES "crw_tag" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("postId", "tagId"))`);
        await queryRunner.query(`INSERT INTO "temporary_crw_post_tags_tag"("postId", "tagId") SELECT "postId", "tagId" FROM "crw_post_tags_tag"`);
        await queryRunner.query(`DROP TABLE "crw_post_tags_tag"`);
        await queryRunner.query(`ALTER TABLE "temporary_crw_post_tags_tag" RENAME TO "crw_post_tags_tag"`);
        await queryRunner.query(`CREATE INDEX "IDX_f24f47df26e67c493b68bfc75b" ON "crw_post_tags_tag" ("postId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6c786f2afb686050d8233fdc6e" ON "crw_post_tags_tag" ("tagId") `);
        await queryRunner.query(`DROP INDEX "IDX_8056740044bde85c6535e4cc6c"`);
        await queryRunner.query(`DROP INDEX "IDX_f4f41beb6142f70af17b37ff50"`);
        await queryRunner.query(`CREATE TABLE "temporary_crw_product_categories_product_category" ("productId" integer NOT NULL, "productCategoryId" integer NOT NULL, CONSTRAINT "FK_8056740044bde85c6535e4cc6c9" FOREIGN KEY ("productId") REFERENCES "crw_product" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_f4f41beb6142f70af17b37ff50f" FOREIGN KEY ("productCategoryId") REFERENCES "crw_product_category" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("productId", "productCategoryId"))`);
        await queryRunner.query(`INSERT INTO "temporary_crw_product_categories_product_category"("productId", "productCategoryId") SELECT "productId", "productCategoryId" FROM "crw_product_categories_product_category"`);
        await queryRunner.query(`DROP TABLE "crw_product_categories_product_category"`);
        await queryRunner.query(`ALTER TABLE "temporary_crw_product_categories_product_category" RENAME TO "crw_product_categories_product_category"`);
        await queryRunner.query(`CREATE INDEX "IDX_8056740044bde85c6535e4cc6c" ON "crw_product_categories_product_category" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f4f41beb6142f70af17b37ff50" ON "crw_product_categories_product_category" ("productCategoryId") `);
        await queryRunner.query(`DROP INDEX "IDX_9463c9a5893b1efb969e9a21c5"`);
        await queryRunner.query(`DROP INDEX "IDX_bc8936d152e18bc99150472594"`);
        await queryRunner.query(`CREATE TABLE "temporary_crw_product_category_closure" ("id_ancestor" integer NOT NULL, "id_descendant" integer NOT NULL, CONSTRAINT "FK_9463c9a5893b1efb969e9a21c59" FOREIGN KEY ("id_ancestor") REFERENCES "crw_product_category" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_bc8936d152e18bc991504725944" FOREIGN KEY ("id_descendant") REFERENCES "crw_product_category" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("id_ancestor", "id_descendant"))`);
        await queryRunner.query(`INSERT INTO "temporary_crw_product_category_closure"("id_ancestor", "id_descendant") SELECT "id_ancestor", "id_descendant" FROM "crw_product_category_closure"`);
        await queryRunner.query(`DROP TABLE "crw_product_category_closure"`);
        await queryRunner.query(`ALTER TABLE "temporary_crw_product_category_closure" RENAME TO "crw_product_category_closure"`);
        await queryRunner.query(`CREATE INDEX "IDX_9463c9a5893b1efb969e9a21c5" ON "crw_product_category_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_bc8936d152e18bc99150472594" ON "crw_product_category_closure" ("id_descendant") `);
    }

    async down(queryRunner) {
        await queryRunner.query(`DROP INDEX "IDX_bc8936d152e18bc99150472594"`);
        await queryRunner.query(`DROP INDEX "IDX_9463c9a5893b1efb969e9a21c5"`);
        await queryRunner.query(`ALTER TABLE "crw_product_category_closure" RENAME TO "temporary_crw_product_category_closure"`);
        await queryRunner.query(`CREATE TABLE "crw_product_category_closure" ("id_ancestor" integer NOT NULL, "id_descendant" integer NOT NULL, PRIMARY KEY ("id_ancestor", "id_descendant"))`);
        await queryRunner.query(`INSERT INTO "crw_product_category_closure"("id_ancestor", "id_descendant") SELECT "id_ancestor", "id_descendant" FROM "temporary_crw_product_category_closure"`);
        await queryRunner.query(`DROP TABLE "temporary_crw_product_category_closure"`);
        await queryRunner.query(`CREATE INDEX "IDX_bc8936d152e18bc99150472594" ON "crw_product_category_closure" ("id_descendant") `);
        await queryRunner.query(`CREATE INDEX "IDX_9463c9a5893b1efb969e9a21c5" ON "crw_product_category_closure" ("id_ancestor") `);
        await queryRunner.query(`DROP INDEX "IDX_f4f41beb6142f70af17b37ff50"`);
        await queryRunner.query(`DROP INDEX "IDX_8056740044bde85c6535e4cc6c"`);
        await queryRunner.query(`ALTER TABLE "crw_product_categories_product_category" RENAME TO "temporary_crw_product_categories_product_category"`);
        await queryRunner.query(`CREATE TABLE "crw_product_categories_product_category" ("productId" integer NOT NULL, "productCategoryId" integer NOT NULL, PRIMARY KEY ("productId", "productCategoryId"))`);
        await queryRunner.query(`INSERT INTO "crw_product_categories_product_category"("productId", "productCategoryId") SELECT "productId", "productCategoryId" FROM "temporary_crw_product_categories_product_category"`);
        await queryRunner.query(`DROP TABLE "temporary_crw_product_categories_product_category"`);
        await queryRunner.query(`CREATE INDEX "IDX_f4f41beb6142f70af17b37ff50" ON "crw_product_categories_product_category" ("productCategoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8056740044bde85c6535e4cc6c" ON "crw_product_categories_product_category" ("productId") `);
        await queryRunner.query(`DROP INDEX "IDX_6c786f2afb686050d8233fdc6e"`);
        await queryRunner.query(`DROP INDEX "IDX_f24f47df26e67c493b68bfc75b"`);
        await queryRunner.query(`ALTER TABLE "crw_post_tags_tag" RENAME TO "temporary_crw_post_tags_tag"`);
        await queryRunner.query(`CREATE TABLE "crw_post_tags_tag" ("postId" integer NOT NULL, "tagId" integer NOT NULL, PRIMARY KEY ("postId", "tagId"))`);
        await queryRunner.query(`INSERT INTO "crw_post_tags_tag"("postId", "tagId") SELECT "postId", "tagId" FROM "temporary_crw_post_tags_tag"`);
        await queryRunner.query(`DROP TABLE "temporary_crw_post_tags_tag"`);
        await queryRunner.query(`CREATE INDEX "IDX_6c786f2afb686050d8233fdc6e" ON "crw_post_tags_tag" ("tagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f24f47df26e67c493b68bfc75b" ON "crw_post_tags_tag" ("postId") `);
        await queryRunner.query(`DROP INDEX "IDX_b096b1be8dd42fe22ddc88821d"`);
        await queryRunner.query(`DROP INDEX "IDX_dc5af49e3e348deae17df11497"`);
        await queryRunner.query(`DROP INDEX "IDX_399b21eccdf612065456fb2610"`);
        await queryRunner.query(`DROP INDEX "IDX_c1cdd15bc1a00fb7500146d9cd"`);
        await queryRunner.query(`DROP INDEX "IDX_487be848a7b34339aec3524e22"`);
        await queryRunner.query(`ALTER TABLE "crw_product_review" RENAME TO "temporary_crw_product_review"`);
        await queryRunner.query(`CREATE TABLE "crw_product_review" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "productId" integer NOT NULL, "title" varchar, "description" text, "rating" float, "userEmail" varchar, "userName" varchar, "userId" varchar, "approved" boolean, CONSTRAINT "UQ_2fa3845bbaf6607041282074f3a" UNIQUE ("slug"))`);
        await queryRunner.query(`INSERT INTO "crw_product_review"("id", "slug", "pageTitle", "pageDescription", "createDate", "updateDate", "isEnabled", "productId", "title", "description", "rating", "userEmail", "userName", "userId", "approved") SELECT "id", "slug", "pageTitle", "pageDescription", "createDate", "updateDate", "isEnabled", "productId", "title", "description", "rating", "userEmail", "userName", "userId", "approved" FROM "temporary_crw_product_review"`);
        await queryRunner.query(`DROP TABLE "temporary_crw_product_review"`);
        await queryRunner.query(`CREATE INDEX "IDX_b096b1be8dd42fe22ddc88821d" ON "crw_product_review" ("approved") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc5af49e3e348deae17df11497" ON "crw_product_review" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_399b21eccdf612065456fb2610" ON "crw_product_review" ("userEmail") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1cdd15bc1a00fb7500146d9cd" ON "crw_product_review" ("rating") `);
        await queryRunner.query(`CREATE INDEX "IDX_487be848a7b34339aec3524e22" ON "crw_product_review" ("productId") `);
        await queryRunner.query(`ALTER TABLE "crw_product_category" RENAME TO "temporary_crw_product_category"`);
        await queryRunner.query(`CREATE TABLE "crw_product_category" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "name" varchar NOT NULL, "mainImage" varchar(300), "description" text, "descriptionDelta" text, "parentId" integer, CONSTRAINT "UQ_273d34ee465b63376bead18bbf2" UNIQUE ("slug"))`);
        await queryRunner.query(`INSERT INTO "crw_product_category"("id", "slug", "pageTitle", "pageDescription", "createDate", "updateDate", "isEnabled", "name", "mainImage", "description", "descriptionDelta", "parentId") SELECT "id", "slug", "pageTitle", "pageDescription", "createDate", "updateDate", "isEnabled", "name", "mainImage", "description", "descriptionDelta", "parentId" FROM "temporary_crw_product_category"`);
        await queryRunner.query(`DROP TABLE "temporary_crw_product_category"`);
        await queryRunner.query(`DROP INDEX "IDX_cb0a2cf3605d77131907fb4664"`);
        await queryRunner.query(`DROP INDEX "IDX_16527a7e9f22a68a274e61d6da"`);
        await queryRunner.query(`DROP INDEX "IDX_787534d5ddf971c1b85d99c88c"`);
        await queryRunner.query(`ALTER TABLE "crw_post_comment" RENAME TO "temporary_crw_post_comment"`);
        await queryRunner.query(`CREATE TABLE "crw_post_comment" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "slug" varchar, "pageTitle" varchar, "pageDescription" varchar, "createDate" datetime NOT NULL DEFAULT (datetime('now')), "updateDate" datetime NOT NULL DEFAULT (datetime('now')), "isEnabled" boolean DEFAULT (1), "postId" integer NOT NULL, "title" varchar, "comment" text, "userEmail" varchar, "userName" varchar, "userId" varchar, "approved" boolean, CONSTRAINT "UQ_0c41e89299843ea6cd5bb1e10b3" UNIQUE ("slug"))`);
        await queryRunner.query(`INSERT INTO "crw_post_comment"("id", "slug", "pageTitle", "pageDescription", "createDate", "updateDate", "isEnabled", "postId", "title", "comment", "userEmail", "userName", "userId", "approved") SELECT "id", "slug", "pageTitle", "pageDescription", "createDate", "updateDate", "isEnabled", "postId", "title", "comment", "userEmail", "userName", "userId", "approved" FROM "temporary_crw_post_comment"`);
        await queryRunner.query(`DROP TABLE "temporary_crw_post_comment"`);
        await queryRunner.query(`CREATE INDEX "IDX_cb0a2cf3605d77131907fb4664" ON "crw_post_comment" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_16527a7e9f22a68a274e61d6da" ON "crw_post_comment" ("userEmail") `);
        await queryRunner.query(`CREATE INDEX "IDX_787534d5ddf971c1b85d99c88c" ON "crw_post_comment" ("postId") `);
        await queryRunner.query(`DROP INDEX "IDX_bc8936d152e18bc99150472594"`);
        await queryRunner.query(`DROP INDEX "IDX_9463c9a5893b1efb969e9a21c5"`);
        await queryRunner.query(`DROP TABLE "crw_product_category_closure"`);
        await queryRunner.query(`DROP INDEX "IDX_f4f41beb6142f70af17b37ff50"`);
        await queryRunner.query(`DROP INDEX "IDX_8056740044bde85c6535e4cc6c"`);
        await queryRunner.query(`DROP TABLE "crw_product_categories_product_category"`);
        await queryRunner.query(`DROP INDEX "IDX_6c786f2afb686050d8233fdc6e"`);
        await queryRunner.query(`DROP INDEX "IDX_f24f47df26e67c493b68bfc75b"`);
        await queryRunner.query(`DROP TABLE "crw_post_tags_tag"`);
        await queryRunner.query(`DROP INDEX "IDX_644eed41dbcadfe2e3e634ba84"`);
        await queryRunner.query(`DROP INDEX "IDX_850a536df6641e90872f905e74"`);
        await queryRunner.query(`DROP INDEX "IDX_0537e4a35e2b1842afc531deab"`);
        await queryRunner.query(`DROP TABLE "crw_user"`);
        await queryRunner.query(`DROP TABLE "crw_theme"`);
        await queryRunner.query(`DROP INDEX "IDX_ce9152d8ef22b16ce86a6e0fd8"`);
        await queryRunner.query(`DROP INDEX "IDX_c717d9265ea3490790ee35edcd"`);
        await queryRunner.query(`DROP INDEX "IDX_a4383ddcc0498cfacd641f9cf8"`);
        await queryRunner.query(`DROP INDEX "IDX_e734039ba75ee043d3c61466de"`);
        await queryRunner.query(`DROP TABLE "crw_product"`);
        await queryRunner.query(`DROP INDEX "IDX_b096b1be8dd42fe22ddc88821d"`);
        await queryRunner.query(`DROP INDEX "IDX_dc5af49e3e348deae17df11497"`);
        await queryRunner.query(`DROP INDEX "IDX_399b21eccdf612065456fb2610"`);
        await queryRunner.query(`DROP INDEX "IDX_c1cdd15bc1a00fb7500146d9cd"`);
        await queryRunner.query(`DROP INDEX "IDX_487be848a7b34339aec3524e22"`);
        await queryRunner.query(`DROP TABLE "crw_product_review"`);
        await queryRunner.query(`DROP TABLE "crw_product_category"`);
        await queryRunner.query(`DROP INDEX "IDX_0977d4805adadb696f735445ee"`);
        await queryRunner.query(`DROP INDEX "IDX_8d98eb30db4dfb464ce54c1957"`);
        await queryRunner.query(`DROP INDEX "IDX_35c1445265a8d5362e06167ae3"`);
        await queryRunner.query(`DROP INDEX "IDX_e47953e4571dce4050c9524443"`);
        await queryRunner.query(`DROP TABLE "crw_post"`);
        await queryRunner.query(`DROP TABLE "crw_tag"`);
        await queryRunner.query(`DROP INDEX "IDX_cb0a2cf3605d77131907fb4664"`);
        await queryRunner.query(`DROP INDEX "IDX_16527a7e9f22a68a274e61d6da"`);
        await queryRunner.query(`DROP INDEX "IDX_787534d5ddf971c1b85d99c88c"`);
        await queryRunner.query(`DROP TABLE "crw_post_comment"`);
        await queryRunner.query(`DROP TABLE "crw_plugin"`);
        await queryRunner.query(`DROP TABLE "crw_page_stats"`);
        await queryRunner.query(`DROP INDEX "IDX_0d115ee42c627f4c5f5ea6d12a"`);
        await queryRunner.query(`DROP INDEX "IDX_8bb01ee9a429f70390bbedbaf6"`);
        await queryRunner.query(`DROP INDEX "IDX_a71afe78a44fdebe245d06c0fb"`);
        await queryRunner.query(`DROP INDEX "IDX_86c22318de90222b57a2f0ac90"`);
        await queryRunner.query(`DROP INDEX "IDX_56caac5bbc2683720ddd655a23"`);
        await queryRunner.query(`DROP TABLE "crw_order"`);
        await queryRunner.query(`DROP TABLE "crw_cms"`);
        await queryRunner.query(`DROP TABLE "crw_attribute"`);
        await queryRunner.query(`DROP TABLE "crw_base_page_entity"`);
    }
}
